name: moontree_utils
description: generic dart utilities shared across moontree repos
version: 1.0.21
homepage: https://github.com/moontreeapp/moontree_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.1.0
  tuple: ^2.0.0
  bs58: ^1.0.2
  convert: ^3.0.2
  collection: ^1.16.0
  crypto: ^3.0.2
  
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0