name: moontree_utils
description: generic dart utilities shared across moontree repos
version: 1.1.7
homepage: https://github.com/moontreeapp/moontree_utils

environment:
  sdk: '>=2.15.0<4.0.0'

dependencies:
  quiver: ^3.1.0
  tuple: ^2.0.0
  bs58: ^1.0.2
  convert: ^3.0.2
  collection: ^1.17.1
  crypto: ^3.0.2
  base32: ^2.1.3
  
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0